/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

import java.awt.Component;

/**
 *
 * @author lg
 */
public class DocBar extends javax.swing.JPanel {
	DocController controller;
	public DocBar () {
		initComponents ();
	}
	public void setController (DocController controller) {
		this.controller = controller;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    newCartaporteButton = new javax.swing.JButton();
    newManifiestoButton = new javax.swing.JButton();
    newDeclaracionButton = new javax.swing.JButton();
    openButton = new javax.swing.JButton();
    saveButton = new javax.swing.JButton();
    createPdfButton = new javax.swing.JButton();
    viewPrintPdf = new javax.swing.JButton();
    closeCurrentButton = new javax.swing.JButton();
    exitButton = new javax.swing.JButton();

    setLayout(new java.awt.GridLayout(9, 0, 0, 3));

    newCartaporteButton.setText("<html>\nNueva<br>Cartaporte");
    newCartaporteButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newCartaporteButtonActionPerformed(evt);
      }
    });
    add(newCartaporteButton);

    newManifiestoButton.setText("<html>Nuevo<br>Manifiesto");
    newManifiestoButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newManifiestoButtonActionPerformed(evt);
      }
    });
    add(newManifiestoButton);

    newDeclaracionButton.setText("<html>Nueva<br>Declaración");
    newDeclaracionButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        newDeclaracionButtonActionPerformed(evt);
      }
    });
    add(newDeclaracionButton);

    openButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/folder-open-outline-filled.png"))); // NOI18N
    openButton.setText("<html>Abrir<br>existente");
    openButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        openButtonActionPerformed(evt);
      }
    });
    add(openButton);

    saveButton.setText("<html>Guardar<br>actual");
    saveButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveButtonActionPerformed(evt);
      }
    });
    add(saveButton);

    createPdfButton.setText("<html>Crear PDF");
    createPdfButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        createPdfButtonActionPerformed(evt);
      }
    });
    add(createPdfButton);

    viewPrintPdf.setText("<html>Ver/Imprimir PDF");
    viewPrintPdf.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        viewPrintPdfActionPerformed(evt);
      }
    });
    add(viewPrintPdf);

    closeCurrentButton.setText("<html>Cerrar<br>actual");
    closeCurrentButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        closeCurrentButtonActionPerformed(evt);
      }
    });
    add(closeCurrentButton);

    exitButton.setText("<html>Salir");
    add(exitButton);
  }// </editor-fold>//GEN-END:initComponents

  private void newCartaporteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCartaporteButtonActionPerformed
		controller.onNewDocument ("cartaporte");		
  }//GEN-LAST:event_newCartaporteButtonActionPerformed

  private void newManifiestoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newManifiestoButtonActionPerformed
		controller.onNewDocument ("manifiesto");		
  }//GEN-LAST:event_newManifiestoButtonActionPerformed

  private void newDeclaracionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDeclaracionButtonActionPerformed
		controller.onNewDocument ("declaracion");
  }//GEN-LAST:event_newDeclaracionButtonActionPerformed

  private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
		controller.onSaveCurrentToJson ();
  }//GEN-LAST:event_saveButtonActionPerformed

  private void createPdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPdfButtonActionPerformed
		controller.onSaveCurrentToPDF ();
  }//GEN-LAST:event_createPdfButtonActionPerformed

  private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
		controller.onOpenDocument ();
  }//GEN-LAST:event_openButtonActionPerformed

  private void closeCurrentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCurrentButtonActionPerformed
		controller.onCloseCurrent ();
  }//GEN-LAST:event_closeCurrentButtonActionPerformed

  private void viewPrintPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPrintPdfActionPerformed
		controller.viewPrintPdf ();
  }//GEN-LAST:event_viewPrintPdfActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton closeCurrentButton;
  private javax.swing.JButton createPdfButton;
  private javax.swing.JButton exitButton;
  private javax.swing.JButton newCartaporteButton;
  private javax.swing.JButton newDeclaracionButton;
  private javax.swing.JButton newManifiestoButton;
  private javax.swing.JButton openButton;
  private javax.swing.JButton saveButton;
  private javax.swing.JButton viewPrintPdf;
  // End of variables declaration//GEN-END:variables
}
