package main;

import java.awt.Dimension;
import javax.swing.ImageIcon;

public class DocPanelDeclaracion extends DocPanel {
	public DocPanelDeclaracion () {
		initComponents ();
		imgTemplateFilepath = DocGlobals.imgDeclaracionFilepath;
		pdfTemplateFilepath = DocGlobals.pdfDeclaracionFilepath;
		docType = "declaracion";
		imageIcon = (ImageIcon) imageLabel.getIcon ();
	}

	//@Override
	public Dimension getPreferredSize () {
		Dimension imageSize = new Dimension (imageIcon.getIconWidth (), imageIcon.getIconHeight ());
		return imageSize;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    txt00 = new main.DocTextArea();
    txt01 = new main.DocTextArea();
    txt02 = new main.DocTextArea();
    imageLabel = new javax.swing.JLabel();

    setBackground(new java.awt.Color(255, 255, 255));
    setPreferredSize(new java.awt.Dimension(1100, 1424));
    setLayout(null);
    add(txt00);
    txt00.setBounds(870, 90, 180, 30);
    add(txt01);
    txt01.setBounds(60, 150, 480, 110);
    add(txt02);
    txt02.setBounds(50, 300, 500, 40);

    imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image-declaracion-vacia-NTA.png"))); // NOI18N
    imageLabel.setAlignmentY(0.0F);
    add(imageLabel);
    imageLabel.setBounds(0, 0, 1100, 1424);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel imageLabel;
  private main.DocTextArea txt00;
  private main.DocTextArea txt01;
  private main.DocTextArea txt02;
  // End of variables declaration//GEN-END:variables

}
