package main;

import java.awt.Component;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

public class DocPanelManifiesto extends DocPanel {

	public DocPanelManifiesto () {
		initComponents ();
		imgTemplateFilepath = DocGlobals.imgManifiestoFilepath;
		pdfTemplateFilepath = DocGlobals.pdfManifiestoFilepath;

		docType = "manifiesto";
		imageIcon = (ImageIcon) imageLabel.getIcon ();
	}

	//@Override
	public Dimension getPreferredSize () {
		Dimension imageSize = new Dimension (imageIcon.getIconWidth (), imageIcon.getIconHeight ());
		return imageSize;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    txt00 = new main.DocTextArea();
    txt01 = new main.DocTextArea();
    txt02 = new main.DocTextArea();
    txt03 = new main.DocTextArea();
    txt04 = new main.DocTextArea();
    txt05 = new main.DocTextArea();
    txt06 = new main.DocTextArea();
    txt07 = new main.DocTextArea();
    txt08 = new main.DocTextArea();
    txt09 = new main.DocTextArea();
    txt10 = new main.DocTextArea();
    txt11 = new main.DocTextArea();
    txt12 = new main.DocTextArea();
    txt13 = new main.DocTextArea();
    txt14 = new main.DocTextArea();
    txt15 = new main.DocTextArea();
    txt16 = new main.DocTextArea();
    txt17 = new main.DocTextArea();
    txt18 = new main.DocTextArea();
    txt19 = new main.DocTextArea();
    txt20 = new main.DocTextArea();
    txt21 = new main.DocTextArea();
    txt22 = new main.DocTextArea();
    txt23 = new main.DocTextArea();
    txt24 = new main.DocTextArea();
    txt25_1 = new main.DocTextArea();
    txt25_2 = new main.DocTextArea();
    txt25_3 = new main.DocTextArea();
    txt25_4 = new main.DocTextArea();
    txt25_5 = new main.DocTextArea();
    txt26 = new main.DocTextArea();
    txt27 = new main.DocTextArea();
    txt28 = new main.DocTextArea();
    txt29 = new main.DocTextArea();
    txt30 = new main.DocTextArea();
    txt31 = new main.DocTextArea();
    txt32_1 = new main.DocTextArea();
    txt32_2 = new main.DocTextArea();
    txt32_3 = new main.DocTextArea();
    txt32_4 = new main.DocTextArea();
    txt33_1 = new main.DocTextArea();
    txt33_2 = new main.DocTextArea();
    txt34 = new main.DocTextArea();
    txt35 = new main.DocTextArea();
    txt36 = new main.DocTextArea();
    txt37 = new main.DocTextArea();
    txt38 = new main.DocTextArea();
    txt39 = new main.DocTextArea();
    txt40 = new main.DocTextArea();
    imageLabel = new javax.swing.JLabel();

    setBackground(new java.awt.Color(255, 255, 255));
    setPreferredSize(new java.awt.Dimension(1100, 1424));
    setLayout(null);
    add(txt00);
    txt00.setBounds(835, 90, 200, 25);
    add(txt01);
    txt01.setBounds(45, 165, 510, 157);
    add(txt02);
    txt02.setBounds(565, 165, 492, 65);
    add(txt03);
    txt03.setBounds(565, 257, 492, 65);
    add(txt04);
    txt04.setBounds(45, 362, 258, 28);
    add(txt05);
    txt05.setBounds(309, 362, 142, 28);
    add(txt06);
    txt06.setBounds(456, 362, 286, 28);
    add(txt07);
    txt07.setBounds(746, 362, 311, 28);
    add(txt08);
    txt08.setBounds(260, 395, 797, 20);
    add(txt09);
    txt09.setBounds(45, 455, 258, 28);
    add(txt10);
    txt10.setBounds(309, 455, 142, 28);
    add(txt11);
    txt11.setBounds(457, 455, 284, 28);
    add(txt12);
    txt12.setBounds(747, 455, 310, 28);
    add(txt13);
    txt13.setBounds(45, 519, 477, 22);
    add(txt14);
    txt14.setBounds(45, 564, 217, 22);
    add(txt15);
    txt15.setBounds(269, 564, 254, 22);
    add(txt16);
    txt16.setBounds(45, 608, 217, 22);
    add(txt17);
    txt17.setBounds(270, 608, 252, 22);
    add(txt18);
    txt18.setBounds(528, 519, 529, 22);
    add(txt19);
    txt19.setBounds(528, 564, 259, 22);
    add(txt20);
    txt20.setBounds(793, 564, 264, 22);
    add(txt21);
    txt21.setBounds(528, 608, 259, 22);
    add(txt22);
    txt22.setBounds(793, 608, 264, 22);
    add(txt23);
    txt23.setBounds(45, 669, 477, 22);
    add(txt24);
    txt24.setBounds(528, 669, 529, 22);
    add(txt25_1);
    txt25_1.setBounds(145, 715, 25, 22);
    add(txt25_2);
    txt25_2.setBounds(425, 715, 25, 22);
    add(txt25_3);
    txt25_3.setBounds(568, 715, 25, 22);
    add(txt25_4);
    txt25_4.setBounds(693, 715, 25, 22);
    add(txt25_5);
    txt25_5.setBounds(792, 700, 265, 55);
    add(txt26);
    txt26.setBounds(45, 791, 477, 22);
    add(txt27);
    txt27.setBounds(528, 791, 529, 22);
    add(txt28);
    txt28.setBounds(45, 850, 110, 348);
    add(txt29);
    txt29.setBounds(160, 850, 364, 348);
    add(txt30);
    txt30.setBounds(528, 850, 112, 348);
    add(txt31);
    txt31.setBounds(644, 850, 137, 348);
    add(txt32_1);
    txt32_1.setBounds(788, 850, 85, 348);
    add(txt32_2);
    txt32_2.setBounds(788, 1206, 85, 30);
    add(txt32_3);
    txt32_3.setBounds(880, 850, 85, 348);
    add(txt32_4);
    txt32_4.setBounds(880, 1206, 85, 30);
    add(txt33_1);
    txt33_1.setBounds(972, 850, 85, 348);
    add(txt33_2);
    txt33_2.setBounds(972, 1206, 85, 30);
    add(txt34);
    txt34.setBounds(45, 1220, 660, 17);
    add(txt35);
    txt35.setBounds(45, 1258, 477, 32);
    add(txt36);
    txt36.setBounds(45, 1316, 477, 40);
    add(txt37);
    txt37.setBounds(528, 1258, 260, 20);
    add(txt38);
    txt38.setBounds(793, 1258, 264, 20);
    add(txt39);
    txt39.setBounds(169, 1359, 353, 20);
    add(txt40);
    txt40.setBounds(528, 1310, 529, 54);

    imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/image-manifiesto-vacia-NTA.png"))); // NOI18N
    imageLabel.setAlignmentY(0.0F);
    add(imageLabel);
    imageLabel.setBounds(0, 0, 1100, 1424);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel imageLabel;
  private main.DocTextArea txt00;
  private main.DocTextArea txt01;
  private main.DocTextArea txt02;
  private main.DocTextArea txt03;
  private main.DocTextArea txt04;
  private main.DocTextArea txt05;
  private main.DocTextArea txt06;
  private main.DocTextArea txt07;
  private main.DocTextArea txt08;
  private main.DocTextArea txt09;
  private main.DocTextArea txt10;
  private main.DocTextArea txt11;
  private main.DocTextArea txt12;
  private main.DocTextArea txt13;
  private main.DocTextArea txt14;
  private main.DocTextArea txt15;
  private main.DocTextArea txt16;
  private main.DocTextArea txt17;
  private main.DocTextArea txt18;
  private main.DocTextArea txt19;
  private main.DocTextArea txt20;
  private main.DocTextArea txt21;
  private main.DocTextArea txt22;
  private main.DocTextArea txt23;
  private main.DocTextArea txt24;
  private main.DocTextArea txt25_1;
  private main.DocTextArea txt25_2;
  private main.DocTextArea txt25_3;
  private main.DocTextArea txt25_4;
  private main.DocTextArea txt25_5;
  private main.DocTextArea txt26;
  private main.DocTextArea txt27;
  private main.DocTextArea txt28;
  private main.DocTextArea txt29;
  private main.DocTextArea txt30;
  private main.DocTextArea txt31;
  private main.DocTextArea txt32_1;
  private main.DocTextArea txt32_2;
  private main.DocTextArea txt32_3;
  private main.DocTextArea txt32_4;
  private main.DocTextArea txt33_1;
  private main.DocTextArea txt33_2;
  private main.DocTextArea txt34;
  private main.DocTextArea txt35;
  private main.DocTextArea txt36;
  private main.DocTextArea txt37;
  private main.DocTextArea txt38;
  private main.DocTextArea txt39;
  private main.DocTextArea txt40;
  // End of variables declaration//GEN-END:variables

	public static void main (String args[]) {
		JFrame frame = new JFrame ("Test for Manifierto Panel");
		frame.setContentPane (new JScrollPane (new DocPanelManifiesto ()));
		frame.setSize (1100, 800);
		frame.setVisible (true);

	}

	public DocTextArea getTxt00 () {
		return txt00;
	}

	public DocTextArea getTxt01 () {
		return txt01;
	}

	public DocTextArea getTxt02 () {
		return txt02;
	}

	public DocTextArea getTxt03 () {
		return txt03;
	}

	public DocTextArea getTxt04 () {
		return txt04;
	}

	public DocTextArea getTxt05 () {
		return txt05;
	}

	public DocTextArea getTxt06 () {
		return txt06;
	}

	public DocTextArea getTxt07 () {
		return txt07;
	}

	public DocTextArea getTxt08 () {
		return txt08;
	}

	public DocTextArea getTxt09 () {
		return txt09;
	}

	public DocTextArea getTxt10 () {
		return txt10;
	}

	public DocTextArea getTxt11 () {
		return txt11;
	}

	public DocTextArea getTxt12 () {
		return txt12;
	}

	public DocTextArea getTxt13 () {
		return txt13;
	}

	public DocTextArea getTxt14 () {
		return txt14;
	}

	public DocTextArea getTxt15 () {
		return txt15;
	}

	public DocTextArea getTxt16 () {
		return txt16;
	}

	public DocTextArea getTxt17 () {
		return txt17;
	}

	public DocTextArea getTxt18 () {
		return txt18;
	}

	public DocTextArea getTxt19 () {
		return txt19;
	}

	public DocTextArea getTxt20 () {
		return txt20;
	}

	public DocTextArea getTxt21 () {
		return txt21;
	}

	public DocTextArea getTxt22 () {
		return txt22;
	}

	public DocTextArea getTxt23 () {
		return txt23;
	}

	public DocTextArea getTxt24 () {
		return txt24;
	}

	public DocTextArea getTxt25_1 () {
		return txt25_1;
	}

	public DocTextArea getTxt25_2 () {
		return txt25_2;
	}

	public DocTextArea getTxt25_3 () {
		return txt25_3;
	}

	public DocTextArea getTxt25_4 () {
		return txt25_4;
	}

	public DocTextArea getTxt25_5 () {
		return txt25_5;
	}

	public DocTextArea getTxt26 () {
		return txt26;
	}

	public DocTextArea getTxt27 () {
		return txt27;
	}

	public DocTextArea getTxt28 () {
		return txt28;
	}

	public DocTextArea getTxt29 () {
		return txt29;
	}

	public DocTextArea getTxt30 () {
		return txt30;
	}

	public DocTextArea getTxt31 () {
		return txt31;
	}

	public DocTextArea getTxt32_1 () {
		return txt32_1;
	}

	public DocTextArea getTxt32_2 () {
		return txt32_2;
	}

	public DocTextArea getTxt32_3 () {
		return txt32_3;
	}

	public DocTextArea getTxt32_4 () {
		return txt32_4;
	}

	public DocTextArea getTxt33_1 () {
		return txt33_1;
	}

	public DocTextArea getTxt33_2 () {
		return txt33_2;
	}

	public DocTextArea getTxt34 () {
		return txt34;
	}

	public DocTextArea getTxt35 () {
		return txt35;
	}

	public DocTextArea getTxt36 () {
		return txt36;
	}

	public DocTextArea getTxt37 () {
		return txt37;
	}

	public DocTextArea getTxt38 () {
		return txt38;
	}

	public DocTextArea getTxt39 () {
		return txt39;
	}

	public DocTextArea getTxt40 () {
		return txt40;
	}

}
